general:
  year: 2025 # The primary year to process
  timezone: Europe/Rome
  env_file: 'credentials.env'

paths:
  static_data_dir: "data"         # Location of static CSV files
  template_path: "templates/mail.html"       # Location of Jinja2 templates
  google_creds_file: "gcloud_key.json" # Path to Google Cloud service account key

# Thresholds and default values for processing
thresholds:
  default_mm: 30      # Default rainfall resistance (mm) if missing in static data
  default_days: 14    # Default treatment interval (days) if missing in static data
  t1_factor: 0.75     # Factor for calculating the lower warning threshold (T1)

driver:
  headless: true
  slow_conn: false
  download_dir: downloads      # Default directory for browser downloads
  user_dir: user_dir           # Chrome user profile directory

smartfarmer:
  username_env: SM_USERNAME
  password_env: SM_PASSWORD

sbr:
  station_id: "103"
  username_env: SBR_USERNAME
  password_env: SBR_PASSWORD

# Gmail settings for sending reports
gmail:
  username_env: GM_USERNAME
  password_env: GM_APPKEY
  host: smtp.gmail.com
  port: 465
  recipients:
    - "tscholl.simon@gmail.com"
    # - "erlhof.latsch@gmail.com"

# Google Sheets settings (optional)
# google_sheets:
#   spreadsheet_name: "Behandlungsübersicht"
#   worksheet_name: "ProcessedData"

logging:
    version: 1
    disable_existing_loggers: false
    formatters: 
        standard:
            format: "%(asctime)s - %(levelname)s - %(filename)s: %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: standard
            level: DEBUG
            stream: ext://sys.stdout
    loggers:
        root:
            handlers: [console]
            level: DEBUG